### ISSUE TITLE
@types in redux-subspace-observable dependencies

### ISSUE THREAD

**Issue by cronon** [ioof-holdings/redux-subspace#101]
### bug in redux-subspace-observable
redux-subspace-observable starting from version 3.0.0 contains @types as dependencies and they conflict with built-in typescript libraries.

### Possible Solution
Move @types/es6-shim and @types/node to devDependencies

**Comment by mpeyper** [comment]
I'm sorry @cronon, this one has slipped past me.

I'm not a typescript user myself, so this sort of this easily confuses me.  I'm happy to accept pull requests to improve or fix type definitions for users.
