### ISSUE TITLE
Provide a guide for contributors

### ISSUE THREAD

**Issue by chaos95** [ioof-holdings/redux-subspace#11]
Github recommends [setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). This enables prospective contributors to avoid rework in order to fit the project's requirements and allows people to join in more readily and with less frustration.

I recommend we use the [Atom contributors' guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) as a template - it's a great example of presenting the most relevant information concisely for this type of guide.

**Comment by mpeyper** [comment]
I think this is a great idea.  I will have a good read of the Atom guide tonight and propose a guide for this repo.  If anyone wants to beat me to it, go ahead and submit yours in a pull request.
