### ISSUE TITLE
TypeError: Object doesn't support property or method 'startsWith' [redux-subspace]

### ISSUE THREAD

**Issue by TheHolyWaffle** [ioof-holdings/redux-subspace#110]
### Is it a bug, feature request or question?

Bug, exception is thrown in console when using Internet Explorer 11

### Which package(s) does this involve?

redux-subspace

### Expected Behavior

No exception is thrown.

### Current Behavior
The following exception is thrown: 
TypeError: Object doesn't support property or method 'startsWith'

https://github.com/ioof-holdings/redux-subspace/blob/ac618ea7a6df5371930b6c38cf6a1e570701b39a/packages/redux-subspace/src/actions/isGlobal.js#L10

### Possible Solution

Don't use String.prototype.startsWith in order to support older environments

| package        | version(s)
| ---------------| -------
| redux          |  4.0.1
| redux-subspace | 3.1.0
| Internet Explorer        |  11

**Comment by mpeyper** [comment]
Happy to accept a PR replacing the call with something more supported.
