### ISSUE TITLE
react-redux-subspace support react-redux 7

### ISSUE THREAD

**Issue by stephen-dahl** [ioof-holdings/redux-subspace#111]
### Input Code
```js
yarn add react-redux-subspace react-redux
```

### Current Behavior
warning " > react-redux-subspace@3.1.0" has incorrect peer dependency "react-redux@^5.0.0".

**Comment by jpeyper** [comment]
Hi @stephen-dahl, thanks for your message.

The upgrade from react-redux v5 to v6 is a major change for us as the internals change significantly

Please see this open PR for the discussions around this and the v7 support that is planned: https://github.com/ioof-holdings/redux-subspace/pull/103

**Comment by jpeyper** [comment]
Sorry, didnt mean to close this... reopening until that PR is resolved.
