### ISSUE TITLE
[redux-subspace-saga] Support redux-saga@^1.0.0

### ISSUE THREAD

**Issue by TheHolyWaffle** [ioof-holdings/redux-subspace#114]
### Is it a bug, feature request or question?

Bug / feature request?

### Which package(s) does this involve?

redux-subspace-saga

### Current behavior

redux-subspace-saga does not work with redux-saga v1.

Currently redux-subspace-saga was written to work with redux-saga version 0.16.2. Since then, redux-saga v1 has been released 6 months ago. It appears from local testing that v1 doesn't work with redux-subspace-saga. Downgrading redux-saga to 0.16.2 makes it work again.

**Comment by TheHolyWaffle** [comment]
From https://github.com/redux-saga/redux-saga/blob/master/CHANGELOG.md it seems that the runSage API has changed and that the subscribe option is no longer used. See https://github.com/ioof-holdings/redux-subspace/blob/master/packages/redux-subspace-saga/src/sagas/subspaced.js#L50.

**Comment by TheHolyWaffle** [comment]
Ok, this fixed it: 

subspaced.js:
```/**
 * Copyright 2017, IOOF Holdings Limited.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { runSaga, stdChannel } from 'redux-saga'
import { getContext, takeEvery } from 'redux-saga/effects'
import { subspace } from 'redux-subspace'
import provideStore from './provideStore'

const subspaced = (mapState, namespace) => {
  const subspaceDecorator = subspace(mapState, namespace)

  return saga => {
    return function*(...args) {
      const channel = stdChannel()
      const parentStore = yield getContext('store')
      const sagaMiddlewareOptions = yield getContext('sagaMiddlewareOptions')

      const store = {
        ...sagaMiddlewareOptions,
        ...subspaceDecorator(parentStore),
        channel: channel
      }

      runSaga(store, provideStore(store, sagaMiddlewareOptions)(saga), ...args)

      yield takeEvery('*', function*(action) {
        store.processAction(action, channel.put)
        yield
      })
    }
  }
}

export default subspaced
```

**Comment by mpeyper** [comment]
Yep, this is part of the larger version upgrade branch I'm currently working on.

https://github.com/mpeyper/redux-subspace/blob/react-redux-v7/packages/redux-subspace-saga/package.json#L39

**Comment by TheHolyWaffle** [comment]
@mpeyper Awesome :) When do you think you'll merge and release? redux-saga v1 is really a must for us

**Comment by mpeyper** [comment]
Anyone following the upgrade will tell you it's likely going to be too long before it's published. I'd like to give you more reassurance than that, but history is not on my side.

If it helps, I just need to fix the examples and add a few test cases, so it should not be long once I find the time, but I'm doing it out of hours at the moment so I can't make any guarantees.
