### ISSUE TITLE
Error on parentSpace

### ISSUE THREAD

**Issue by dhirajataws** [ioof-holdings/redux-subspace#115]
### Is it a bug ?

ERROR in ../node_modules/react-redux-subspace/es/index.js 92:15-26
"export 'parentSpace' was not found in 'redux-subspace'

### Which package(s) does this involve?

    "react-redux-subspace": "3.1.0",

### Current Behavior

ERROR in ../node_modules/react-redux-subspace/es/index.js 92:15-26
"export 'parentSpace' was not found in 'redux-subspace'

### Your Setup

Running using webpack-dev-server

| package        | version(s)
| ---------------| -------

| react-redux-subspace |3.1.0

**Comment by dhirajataws** [comment]
is this an error
ERROR in ../node_modules/react-redux-subspace/es/index.js 92:15-26
"export 'parentSpace' was not found in 'redux-subspace'

**Comment by mpeyper** [comment]
The export in `react-redux-subspace` is `parentSpaced` not `parentSpace`. 

`parentSpace` is the underlying utility from the core `redux-subspace` package that `ParentSpaceProvider` uses.

**Comment by dhirajataws** [comment]
Thanks @mpeyper
