### ISSUE TITLE
Basic subspace example incorrect in docs

### ISSUE THREAD

**Issue by conartist6** [ioof-holdings/redux-subspace#116]
The [subspace quick-start](https://github.com/ioof-holdings/redux-subspace/tree/master/packages/redux-subspace#quick-start) doc is missing `(store)` calls. The correct code would be:
```
const todoStore = subspace((state) => state.todo)(store)
const counter1Store = subspace((state) => state.counter1, 'counter1')(store)
const counter2Store = subspace((state) => state.counter2, 'counter2')(store)
```

**Comment by mpeyper** [comment]
Lol, yep. Your absolutely correct.

I'll fix it up next time I'm at my laptop, or you (or someone) can file a PR for it.
