### ISSUE TITLE
Allow store to be passed to SubspaceProvider as props

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-subspace#13]
I was looking through the [slides](http://www.slideshare.net/VivianFarrell/scaling-react-and-redux-at-ioof) @vivian-farrell shared from the MelbJS event and I have a suggestion for an alternative way to provide the store to the subspace.

On slide 44, the following snippet is shown:
```
ReactDOM.render(
    <Provider store={reduxStore}>
        <ThemeProvider theme={theme}>
            {React.createElement(scope.component(), {configuration: scope.configuration})}
        </ThemeProvider>
    </Provider>
element[0]);
```

If the intention is to eventually have all the micro-frontends wrapped in a `SubspaceProvider` then it may end up looking something like:
```
ReactDOM.render(
    <Provider store={reduxStore}>
        <ThemeProvider theme={theme}>
            <SubspaceProvider mapState={state => state.component}>
                {React.createElement(scope.component(), {configuration: scope.configuration})}
            </SubspaceProvider>
        </ThemeProvider>
    </Provider>
element[0]);
```

At this point, the only reason to use `Provider` in this scenario is for `SubspaceProvider` to use.  I think it would be nice if it could be written as:
```
ReactDOM.render(
    <ThemeProvider theme={theme}>
        <SubspaceProvider store={reduxStore} mapState={state => state.component}>
            {React.createElement(scope.component(), {configuration: scope.configuration})}
        </SubspaceProvider>
    </ThemeProvider>
element[0]);
```

`SubspaceProvider` would need to be changed to look for a store either in props or in the context before applying the subspacing logic.  

We would need to decide what would take preference if both were found.  My gut feeling is that props should override context as it is more deliberately declared, but I'm sure arguments could be made for the alternative.

Thoughts?

**Comment by vivian-farrell** [comment]
The examples from the presentation are actually a bit misleading because actually you only ever use Provider once, at your root node. ReactDOM.render is generally only called once at the root of your React App. However, SubspaceProvider is use around every micro frontend and potentially at varying levels of the component hierarchy. So this proposal doesn't actually optimise much.

**Comment by mpeyper** [comment]
I agree that there isn't much optimisation here.  The introduction of the `subspaced` HOC has also rendered this suggestion pointless as you could now write:

```
ReactDOM.render(
    <Provider store={reduxStore}>
        <ThemeProvider theme={theme}>
            {React.createElement(subspaced(state => state.component)(scope.component()), {configuration: scope.configuration})}
        </ThemeProvider>
    </Provider>
element[0]);
```

I'll mark this as as wontfix and close it off
