### ISSUE TITLE
Diagram to better explain how to use this library

### ISSUE THREAD

**Issue by vivian-farrell** [ioof-holdings/redux-subspace#27]
I feel that it's not clear in the readme what this library does and why you'd use it. I want to create a diagram that shows the relationship between an exported component, a parent app and global store. I also want to highlight the limitation of react-redux that inspired this library.

**Comment by mpeyper** [comment]
Sounds good. A picture tells 1000 words and all...

**Comment by jpeyper** [comment]
Perhaps its even more important now with the 2.0 update incoming.... it just got a whole lot more complex (but simpler at the same time).

**Comment by ms88privat** [comment]
Any update here?

**Comment by jpeyper** [comment]
Honestly, not really.

@mpeyper has been working on improving the docs in his spare time.

@ms88privat Is there a part of redux-subspace that you're struggling with, or an area of the docs you feel is especially confusing that we can help with?

**Comment by jpeyper** [comment]
Just on topic of this issue, I think it should be closed in favor of #52

**Comment by ms88privat** [comment]
@jpeyper I want to try this library soon. 

For me it is not really clear if I need to communicate between different subspaces and how this would look like. Especially a subspace to its parent space. 

Normally I would use actions for this, but now they are subspaced. This is correct, because it shouldn't know about the parent app. 

So I would define callback props like we do it with normal components? e.g. pseudo code:
```js
<ParentApp>
  <SubspacedApp onCounterCange={parentFunction} />
</ParentApp>
```

**Comment by mpeyper** [comment]
@ms88privat I would try not to communicate between subspaces as much as possible. The point of this library is to isolate the components from each other, which makes that sort of communication difficult to control.

That said, we have the concept of [global actions](https://github.com/ioof-holdings/redux-subspace/blob/master/docs/advanced/ScopingActions.md#global-actions) which can be used to break out of subspaces. These can be picked up by a parent's or a sibling's reducer, even if they are subspaced. Just note that all reducers will receive a global action, so be careful of unexpected crosstalk.

Callback props are definitely an option too if you're more comfortable with that. It will give you more control of which components are communicating with each other, but will take more effort to set up and maintain.

**Comment by mpeyper** [comment]
If anyone is looking to pick this up, the [`redux-doghouse`](https://github.com/DataDog/redux-doghouse) docs have a diagram that I think is the sort of thing @vivian-farrell had in mind for this.

I'm not saying steal it, but to use it as inspiration for this.

**Comment by mpeyper** [comment]
I've given up wanting this.  Happy if someone whats to contribute something, but I'm closing this now.
