### ISSUE TITLE
Subspaced Saga - React to global action

### ISSUE THREAD

**Issue by piotrkochan** [ioof-holdings/redux-subspace#304]
### Is it a bug, feature request or question?

Question

### Which package(s) does this involve?

redux-subspace-saga

### Input Code

Subspaced saga:
```js
function* doThings() {
 // not firing
}

export default function* rootSaga() {
    yield all([
        takeEvery(GLOBAL_ACTION, doThings),
```

Root saga:

```js
export default function* rootSaga() {
   call(subspaced(state=>state.a, "mySubspace")(selector)),
}
```

### Expected Behavior

I would like to catch actions fired in the global space.

### Current Behavior

Subspaced saga reacts only to namespaced actions.

### Possible Solution

Maybe there is a way to do that. Of course I can `takeEvery(GLOBAL_ACTION);` in global saga and re-yield them as namespaced.

**Comment by mpeyper** [comment]
All namespace boundaries (whether they be for reducers, sagas or anything else) are supposed to process any relevantly namespaced actions and [global actions](https://ioof-holdings.github.io/redux-subspace/docs/advanced/ScopingActions.html#global-actions).

How are you dispatching the global action? As a plain action into the global store or using the `globalAction` utility/`globalActions` middleware?

**Comment by piotrkochan** [comment]
I'm just dispatching plain action but I'll try with the globalAction utility, thanks!

**Comment by mpeyper** [comment]
Yeah, that would explain it. Let me know how you go.

**Comment by piotrkochan** [comment]
It works
