### ISSUE TITLE
Should lib folder be checked in?

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-subspace#5]
Should the [lib folder](https://github.com/ioof-holdings/redux-subspace/tree/master/lib) be checked in?  I would have thought lib would be generated as part of some CI build and pushed into npm, but would not need to exist in git.

I'm happy to remove it, just wondered if there was reason for it being there.

**Comment by vivian-farrell** [comment]
It's there until I sort out the npm package. I don't really see the need for a CI build unless you think there's going to be lots of ongoing releases. I think it's overkill.

**Comment by mpeyper** [comment]
Personally, I think that's a good reason to have one. So I don't have to remember what I'm doing every time I want to do a release :P

**Comment by mpeyper** [comment]
@vivian-farrell has there been any more movement on this yet?

FYI for others, Vivian and myself discussed it and decided we would set up a CI build.  Thanks to @chaos95 for getting us started with #10

**Comment by vivian-farrell** [comment]
We can delete lib now since I published to NPM a couple of weeks ago. For CI I'm still thinking we don't publish with travis because of the need to version bump and wanting control over when and what is published . Other open source libraries like redux don't appear to use travis for publishing. 

I can cleanup the lib folder later today.

**Comment by mpeyper** [comment]
Who can push to npm? I noticed the previous versions in npm appear to be pushed by your account.  Are there specific permissions required?

Perhaps the publishing procedure should be documented somewhere.

**Comment by chaos95** [comment]
For reference, redux Travis config: https://github.com/reactjs/redux/blob/master/.travis.yml

They run a source check (e.g. lint), a build (e.g. babel/webpack) and then examples (e.g. specs). As @vivian-farrell mentioned, nowhere do they publish or push anything from the Travis build. The Travis build _is_ used to verify PRs, and to show a build badge in the README. I feel like both of those are good use cases for our Travis config also, and reasonably straightforward to set up.

**Comment by vivian-farrell** [comment]
Lib has been deleted now. Closing...
