### ISSUE TITLE
Using the HOC solution will cause a remount of passed component instead of a re-render.

### ISSUE THREAD

**Issue by Shadowantz** [ioof-holdings/redux-subspace#55]
I needed to render some components inside a map method but if I use the provided HOC solution, the component passed  to the HOC will be remounted every time it receives props.
Using the 'SubspaceProvider' class, everything works as expected.
Is this intended?

**Comment by mpeyper** [comment]
Do you mean something like:

```
class MyComponent extends React.Component {
  render () {
    return (
      <div>
        this.props.someList.map(item => subspaced(state => state.whatever)(OtherComponent))
      </div>
  }
}
```

vs.

```
class MyComponent extends React.Component {
  render () {
    return (
      <div>
        this.props.someList.map(item => <SubspaceProvider mapState={state => state.whatever}<OtherComponent /></SubspaceProvider>)
      </div>
  }
}
```

**Comment by Shadowantz** [comment]
Yes, this is the case pretty much.
Thanks for explaining! Now I know why :).
Sorry for a wrong issue report.
