### ISSUE TITLE
Clean up subspaceWrappers

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-subspace#6]
I think [subspaceWrappers](https://github.com/ioof-holdings/redux-subspace/blob/master/src/subspaceWrappers.js) is not great and should be split into a few files that better define the functions.

I was thinking of moving them to something like:
`getSubState` -> `utils/subState.js`
`subStateDispatch` -> `utils/dispatch.js`
`namespacedDispatch` -> `utils/dispatch.js`
`namespacedReducer` -> `reducers/namespaced.js`

If going for a folder structure like above, I would also move `SubspaceProvider.jsx` into a components directory and change the extension to just be `.js`.

Thoughts?

**Comment by jpeyper** [comment]
I think breaking it out into seperate files is a good idea (moving into other folders may be a little overkill for a total of 6 files, but I'm not against it).

As far as `jsx` -> `js` goes, my rule is that if it is straight javascript, its `.js`, if it has jsx in it, its a `.jsx`

I know webpack and imports don't care and will treat the two interchangeably, but I still like to think that you can't throw a jsx at a javascript runtime environment and have it work, so it shouldn't be `.js`

... but thats more a personal thing and I'm happy to have everything in this project be `.js` if thats the more accepted way in the javascript community (honestly don't know enough about it to really have an opinion)

**Comment by mpeyper** [comment]
Fundamentally, I agree with you on the jsx vs. js debate, but I doubt we will have 100% agreement on that... However, `SubspaceProvider` does not contain any jsx and was mislabelled from the start. :)

**Comment by vivian-farrell** [comment]
Agree on the file extensions. Jsx is better because it allows you to optimise the compile process. File splitting is a personal preference. For something like this, I'm actually ok with everything in the same file. Have a look at react-redux. Try not to get carried away with over structuring, because it can make it harder to read.

**Comment by mpeyper** [comment]
@vivian-farrell you mean [this one](https://github.com/reactjs/react-redux/tree/master/src) with all files and structure? I modelled the proposed structure off that repo.

There are quite a few jsx files with the js extension that should probably also be changed then.

**Comment by vivian-farrell** [comment]
Yeah that's the one. If your structure is inspired by that, then I reckon it's on the right track.
