### ISSUE TITLE
Create a redux-subspace logo

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-subspace#60]
I've [previously stated](https://twitter.com/michaelpeyper/status/904650745298825216) that I would like to get a (cool) logo for this library, but having zero artistic ability myself, I'm reaching out to anyone who does.

There was [one attempt a while ago](https://github.com/ioof-holdings/redux-subspace/pull/48) with some notes in it of what I'm after but here are some general ideas (you don't have to use all of them):

- minimalistic, clean design
- space themed (stars, rockets, planets, moons, etc.)
- tied in to the [Redux logo](https://github.com/reactjs/redux/tree/master/logo) would be nice (e.g. [redux-saga](https://github.com/redux-saga/redux-saga/tree/master/logo)), keeping in mind we integrate with a lot of other libraries of the redux ecosystem as well, so being able to switch out the redux logo for their logo is a win
- could use the ["IOOF greens"](https://www.ioofonline.com.au/images/logo.svg) for colour inspiration
- ignore everything I've said and make something awesome

**Comment by matthewhartman** [comment]
I had a little attempt this morning. I'll send a PR for it :)

**Comment by mpeyper** [comment]
I've given up waiting for something I like.  Closing.
