### ISSUE TITLE
[subspace-saga]

### ISSUE THREAD

**Issue by Crazy-Ivan** [ioof-holdings/redux-subspace#67]
Many times my saga uses data from global scope with connection with local scope. Is there any option to select things from the root store?

**Comment by jpeyper** [comment]
Hi @Crazy-Ivan,

The purpose of subspaced sagas is to isolate them from the global store, so there is no direct way to access the root store from inside the saga

[redux-subspace-wormhole](https://github.com/ioof-holdings/redux-subspace/tree/master/packages/redux-subspace-wormhole) is there to provide global (root) state into your subspaces, and therefore inside your subspaced saga.

**Comment by mpeyper** [comment]
In addition to wormholes, the [`mapState` selector of the `subspaced` saga wrapper](https://ioof-holdings.github.io/redux-subspace/packages/redux-subspace-saga/docs/api/subspaced.html#arguments) provides the `rootState` as the second parameter which can be merged into the subspaces state.

**Comment by mpeyper** [comment]
Hi @Crazy-Ivan, is there anything left to do on this issue or can I close it?

**Comment by Crazy-Ivan** [comment]
Nothing new. Please close it.
