### ISSUE TITLE
How to use with reselect?

### ISSUE THREAD

**Issue by Crazy-Ivan** [ioof-holdings/redux-subspace#68]
Could you provide an example how to use redux-subspace with reselect? 
I have a problem with react-redux-subspace and reselect. 
I use very complex selectors which based on root scope and have to base on a local scope as well.

**Comment by jpeyper** [comment]
Hi @Crazy-Ivan,

Its a bit hard to provide an example without understanding your use case a little better. To our knowledge that aren't any issues using reselect with react-redux-subspace.

Are you able to provide any code of your complex selector and how you used it with subspace, or provide a few more details on the problem you are seeing?

Have you considered using [redux-subspace-wormhole](https://github.com/ioof-holdings/redux-subspace/tree/master/packages/redux-subspace-wormhole) to provide root state to your subspace?

**Comment by Crazy-Ivan** [comment]
Hi @jpeyper,

redux-subspace-wormhole can be the answer. Base on documentation  I see that I have to explicit map which part of the global state will be injected. Which breaks a bit open/close principle. I had to edit it every time I will need add selector which use part of the global scope, I didn't inject before. 

```js
const store = createStore(rootReducer, 
applyMiddleware(wormhole((state) => state.globalCarsCollection, 'globalCarsCollection')), 
applyMiddleware(wormhole((state) => state.globalColors, 'globalColors')), 
applyMiddleware(wormhole((state) => state.globalPrices, 'globalPrices')), 
)
```

```js
export const getSomthingImportant = () => createSelector(
    scopedListOfIdsSelector, // [{carId, colorId, priceId},...]
    globalCarsCollectionSelector,
    globalColorsSelector,
    globalPricesSelector,
    (scopedListOfIds, globalCarsCollection, globalColors, globalPrices) => {
      return something
    }
);
```

In the example above  globalCarsCollectionSelector, globalColorsSelector, globalPricesSelector are functions which expect rootState, scopedListOfIdsSelector expect scoped state. Injecting global scope into local scope is a trick which could work for reselect (if we won't have a naming collision). However, we have to be sure that we inject everything and be sure that there is no naming collision. Do you know how it could be solved?

Thank you in advance

**Comment by mpeyper** [comment]
@Crazy-Ivan, just so I can be sure I'm understanding correctly, you want to use reselect to create a selector to use in:

a) mapStateToProps param of a `connect` HOC used **inside** a subspace
b) mapState param of a `subspaced` HOC
c) mapState param of a `SubspaceProvider`

> Base on documentation I see that I have to explicit map which part of the global state will be injected. Which breaks a bit open/close principle.

We do have a RFC open (#57) on how the wormhole api could be improved if you would like to add any thoughts you have on it (positive and/or negative).

**Comment by Crazy-Ivan** [comment]
a) mapStateToProps param of a connect HOC used inside a subspace

**Comment by mpeyper** [comment]
Oh, I forgot to mention about reselect...

Once the global values are in the subspace's state, you can use reselect like normal:

```js
export const getSomthingImportant = () => createSelector(
    scopedListOfIdsSelector, // from the local state for the subspace, e.g. state.scopedListOfIds
    globalCarsCollectionSelector, // from state.globalCarsCollection or state.root.globalCarsCollection
    globalColorsSelector, // from state.globalColors or state.root.globalColors
    globalPricesSelector, // from state.globalPrices or state.root.globalPrices
    (scopedListOfIds, globalCarsCollection, globalColors, globalPrices) => {
      return something
    }
);
```

**Comment by Crazy-Ivan** [comment]
Thank you, that is very helpful. One question. Is there any option to get the name of the subspace inside a wrapped component? ('react-redux-subspace')

**Comment by mpeyper** [comment]
> One question. Is there any option to get the name of the subspace inside a wrapped component? ('react-redux-subspace')

Nothing that is officially supported.

Technically, if you have [access to the store directly](https://github.com/reactjs/react-redux/issues/108#issuecomment-140778557), then it will have a `namespace` field on it that will be the namespace of the current subspace.

**Comment by mpeyper** [comment]
Hi @Crazy-Ivan, is there anything left to do on this issue or can I close it?

**Comment by Crazy-Ivan** [comment]
Use case: [Mobile app]  I have several screens which make up one search functionality (search screen, specific filter screens, etc). Screens are connected together via navigations system in a layer above component definition. I had to use this search functionality in many places but the state should not be shared. To be able to navigate correctly between screens inside search functionality ( results screen -> main filter screen -> specific filter screen), I need to now on which namespace a user is.

**Comment by mpeyper** [comment]
Hi @Crazy-Ivan,  just wondering how you are going with this?

I'm still not sure if there is anything actionable for this item.  Happy to discuss further, or close if you feel there is nothing more to do.
