### ISSUE TITLE
[react-redux-subspace] Couldn't find preset "env" relative to directory 

### ISSUE THREAD

**Issue by Crazy-Ivan** [ioof-holdings/redux-subspace#69]
Hey, 

When I tried to build my solution I get an error "... /node_modules/react-redux-subspace/lib/index.js: Couldn't find preset "env" relative to directory".  Any clue how to deal with it?  [react-native]

**Comment by mpeyper** [comment]
The only thing I can think of is the [babel preset](https://babeljs.io/docs/plugins/preset-env/).  We install it as a [dev dependency](https://github.com/ioof-holdings/redux-subspace/blob/master/packages/redux-subspace/package.json#L32) and define it in our [`.babelrc`](https://github.com/ioof-holdings/redux-subspace/blob/master/packages/redux-subspace/.babelrc#L2) for use in our build pipeline, but I wouldn't have thought you would need to install it to.

Are you webpacking (or other bundler) your project and seeing this?

**Comment by mpeyper** [comment]
I wonder if it's the same as gaearon/redux-thunk#43?

Perhaps we should be excluding the `.babelrc` file from out npm packages?

**Comment by Crazy-Ivan** [comment]
I think it could be it

**Comment by mpeyper** [comment]
Yeah, [it appears to be a thing](https://jaketrent.com/post/dont-publish-babelrc-npm/).  I'll try to get a version out without those for you ASAP.

As a quick and dirty fix, try running `npm i -D babel-preset-env` and see if that lets the build go through?

**Comment by mpeyper** [comment]
@Crazy-Ivan Of course, you are welcome to submit a PR to ignore them if you want to speed it up a bit.  Just needs a `.babelrc` line to the [`.npmignore` file](https://github.com/ioof-holdings/redux-subspace/blob/master/packages/react-redux-subspace/.npmignore) in each of the packages.

**Comment by mpeyper** [comment]
@Crazy-Ivan #70 has been published now, let me know if it helped.
