### ISSUE TITLE
Support alternate store keys.

### ISSUE THREAD

**Issue by conartist6** [ioof-holdings/redux-subspace#89]
Redux-subspace should configuration for attaching to alternate redux store keys.

This will support usage in situations where there may actually be more than one Redux store, though that is something that this library will hopefully remove the need for.

Also it will support situations like mine, where I am building a set of reusable, redux-bound wrapper components which return rendering control to their parent context. In this case in order for the application to function properly my subspace for the wrappers needs to have its own store key, because using  SubspaceProvider on the `store` context key would prevent the wrapped application components from accessing the non-subspaced store.

**Comment by conartist6** [comment]
Huh, force pushing seems to be uniquely ugly for issues references. TIL.

**Comment by mpeyper** [comment]
Hi @conartist6,

Yes this sounds like a good idea, I'll continue the discussions in #90

**Comment by mpeyper** [comment]
Feature release in v4
